In [1]:
!pip install numpy

In [5]:
import numpy as np
#cach 1
my_list = [1, 9, 15, 39]
print('Python list: ', my_list)

my_numby_array = np.array(my_list)
print('Numby array:', my_numby_array)

#cach 2
a = np.array([1, 9, 15, 39])
print(a)

Python list:  [1, 9, 15, 39]
Numby array: [ 1  9 15 39]
[ 1  9 15 39]


In [6]:
c = np.array([(1, 2, 3), (4, 5, 6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [7]:
d = np.array([[[1., 2., 3.],[4.,5.,6.]],[[7.,8.,9.],[10,11,12]]])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [8]:
e = np.zeros((2,2))
f = np.ones((3,3))
print('Zero matrix: \n', e)
print('One matrix: \n', f)

Zero matrix: 
 [[0. 0.]
 [0. 0.]]
One matrix: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
e = np.array([[1.,2.,3.],[4.,5.,6.]])
print(e)
print(e.shape)
f = e.reshape(3,2)
print(f)
g = np.array([[[1.,2.,3.],[4.,5.,6.]],[[7.,8.,9.],[10.,11.,12.]]])
print(g)
print(g.shape)
h = g.reshape(3,4)
print('reshape (3,4)\n',h)
j = g.reshape(3,2,2)
print('reshape (3,2,2)\n',j)
k = g.reshape(2,3,2)
print('reshape (2,3,2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3,4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3,2,2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2,3,2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [11]:
e = np.array([[1.,2.,3.],[4.,5.,6.]])
f = e.flatten()
print(f)
g = np.array([[[1.,2.,3.],[4.,5.,6.]],[[7.,8.,9.],[10.,11.,12.]]])
j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [12]:
f = np.array([1.,2.,3.])
g = np.array([4.,5.,6.])
h_stack = np.hstack((f,g))
print('Horizontal Append\n',h_stack)
v_stack = np.vstack((f,g))
print('Vertical Append\n',v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


In [14]:
a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)
b = np.random.randint(100, size=(3,5))
print('Random 2-D array\n', b)
c = np.random.randint(100, size=(3,4,3))
print('Random 3-D array\n', c)

Random 1-D array
 [67  8 60 90 90]
Random 2-D array
 [[60 72 55 73 31]
 [47 82 93 90 24]
 [71 23 54  4 82]]
Random 3-D array
 [[[86 61 31]
  [37 26 48]
  [ 3 65 32]
  [60 24 42]]

 [[74 91 50]
  [98 83 82]
  [90  3 48]
  [80 70 49]]

 [[39 28 55]
  [91 92 39]
  [83 12 51]
  [24 80 98]]]


In [15]:
a = np.random.rand(5)
print('Random 1-D array\n',a)
b = np.random.rand(3,4)
print('Random 2-D array\n',b)
c = np.random.rand(3,4,3)
print('Random 3-D array\n',c)

Random 1-D array
 [0.91562802 0.12582393 0.49150806 0.52228574 0.42527203]
Random 2-D array
 [[0.15382317 0.14343286 0.44945771 0.35083739]
 [0.78813172 0.55853034 0.73339323 0.38977056]
 [0.11999531 0.42459216 0.11247619 0.61775067]]
Random 3-D array
 [[[0.26561963 0.98718486 0.93381064]
  [0.27105477 0.84486852 0.84714847]
  [0.1735459  0.82461835 0.01250697]
  [0.40381243 0.08394626 0.813737  ]]

 [[0.1257928  0.5815627  0.23810224]
  [0.96641566 0.41237979 0.88936851]
  [0.75799487 0.66687949 0.14127242]
  [0.01139233 0.93916388 0.43225198]]

 [[0.47212621 0.92210535 0.02885641]
  [0.15947054 0.69790018 0.93190446]
  [0.05288956 0.2131762  0.70355521]
  [0.86947965 0.95424486 0.62786483]]]


In [16]:
a = np.random.normal(5, 0.5, 10)
print(a)

[4.66669494 5.99302123 5.0740071  4.69079219 6.05382266 4.17308639
 5.58167201 4.96888689 4.87700812 4.8383202 ]


In [17]:
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)
b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size = (3,5))
print(b)

16
[[12 12  2  4 18]
 [14  2 14 16 20]
 [ 2 20 18  2  8]]


In [19]:
A = np.matrix(np.ones((5,5)))
print('The matrix\n',A)
np.array(A)[2] = 2
print('Change values of third row with array\n',A)
np.asarray(A)[2] = 2
print('Change values of third row with asarray\n',A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
a = np.arange(1, 20)
print(a)
b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [21]:
a = np.linspace(1., 5., num = 10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [22]:
a = np.array([(1,2,3),(4,5,6)])
print(a)
print('first row:', a[0])
print('second row: ',a[1])

print('Second column: ',a[:,1])
print('first column: ',a[:,0])
print('First two values of second row', a[1, :2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row:  [4 5 6]
Second column:  [2 5]
first column:  [1 4]
First two values of second row [4 5]


In [23]:
!pip install pandas

In [24]:
import pandas as pd
a = pd.Series([1.,2.,3.])
print(a)
print('First value:',a[0])
b = pd.Series([1.,2.,3.], index=['a','b','c'])
print(b)
print('First value:',b['a'])

calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64


In [26]:
h = np.array([[1, 2], [3,4]])
df_h = pd.DataFrame(h)
print('DataFrame:\n', df_h)

numpy_h = np.array(df_h)
print('Numby array: \n', numpy_h)

DataFrame:
    0  1
0  1  2
1  3  4
Numby array: 
 [[1 2]
 [3 4]]


In [27]:
dic = {'Name':['John','Smith'], 'Age':[30,40]}
df_dic = pd.DataFrame(dic)
print(df_dic)

    Name  Age
0   John   30
1  Smith   40


In [28]:
r = np.random.randn(20,4)
df = pd.DataFrame(r, columns=['so1','so2','so3','so4'])
print(df.head())

        so1       so2       so3       so4
0 -1.216430 -0.528415  0.347269 -0.797569
1 -0.002195  0.471888 -0.546771 -1.687636
2 -1.866271  1.746783 -1.081051  0.077896
3 -0.066972  0.938460 -0.255968 -3.327937
4 -0.437909 -0.354066  0.275531 -0.169823


In [30]:
r = np.random.randn(20,4)
df = pd.DataFrame(r, columns=['so1','so2','so3','so4'])
print(df.head())

print('Chon cot so1\n',df['so1'])
print('Chon nhieu dong\n', df[0:3])
print('Chon nhieu cot\n', df[['so1','so3']])
print('Chon nhieu dong, nhieu cot\n', df.iloc[:3, :2])
df = df.drop(columns=['so1','so4'])
print(df)

        so1       so2       so3       so4
0  0.974383 -1.231715  0.826310 -0.330612
1 -0.200297 -1.440354  1.759048 -0.936034
2  1.363433 -0.039522  0.102360  0.973179
3 -1.512031 -0.894343  0.030682 -0.181576
4  1.929499 -0.624190  0.145237  0.956015
Chon cot so1
 0     0.974383
1    -0.200297
2     1.363433
3    -1.512031
4     1.929499
5    -0.039653
6    -0.892864
7     1.218733
8     0.190528
9     1.124991
10   -1.290867
11   -1.427527
12   -0.371235
13    0.328341
14   -1.504830
15    0.217898
16    0.142528
17   -0.345656
18    0.374572
19    0.653513
Name: so1, dtype: float64
Chon nhieu dong
         so1       so2       so3       so4
0  0.974383 -1.231715  0.826310 -0.330612
1 -0.200297 -1.440354  1.759048 -0.936034
2  1.363433 -0.039522  0.102360  0.973179
Chon nhieu cot
          so1       so3
0   0.974383  0.826310
1  -0.200297  1.759048
2   1.363433  0.102360
3  -1.512031  0.030682
4   1.929499  0.145237
5  -0.039653  1.179670
6  -0.892864 -0.038405
7   1.218733 -0.017334


In [31]:
df1 = pd.DataFrame({'Name':['John','Smith','Paul'],'Age': [25,30,50]},index = [0, 1, 2])
df2 = pd.DataFrame({'Name':['Adam','Smith'],'Age': [26,11]},index = [3,4])

df_concat = pd.concat([df1,df2])
print('Concate two DataFrame\n', df_concat)
print('Drop duplicatevalues in DataFrame\n', df_concat.drop_duplicates('Name'))
print('Sort values in DataFrame\n', df_concat.sort_values('Age'))

df_rename = df_concat.rename(columns={'Name':'Surname','Age':'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicatevalues in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


In [32]:
path = '/content/sample_data/california_housing_train.csv'
COLUMNS = ['longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population']
df_csv = pd.read_csv(path, skipinitialspace=True,names=COLUMNS, index_col=False)
print(df_csv.head())
print(df_csv.shape)
df_csv1 = pd.read_csv(path,skipinitialspace=True, index_col=False)
print(df_csv1.head())
print(df_csv1.shape)

     longitude   latitude  housing_median_age  total_rooms  total_bedrooms  \
0    longitude   latitude  housing_median_age  total_rooms  total_bedrooms   
1  -114.310000  34.190000           15.000000  5612.000000     1283.000000   
2  -114.470000  34.400000           19.000000  7650.000000     1901.000000   
3  -114.560000  33.690000           17.000000   720.000000      174.000000   
4  -114.570000  33.640000           14.000000  1501.000000      337.000000   

    population  
0   population  
1  1015.000000  
2  1129.000000  
3   333.000000  
4   515.000000  
(17001, 6)
   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0 

/tmp/ipykernel_4403/3501200421.py:3: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df_csv = pd.read_csv(path, skipinitialspace=True,names=COLUMNS, index_col=False)


In [33]:
path = '/content/sample_data/california_housing_test.csv'
df_csv = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv.head())
print(df_csv.groupby(['longitude']).mean().head())
print(df_csv.groupby(['longitude'])['latitude'].min().head())
print(df_csv.groupby(['longitude', 'housing_median_age'])['latitude'].max().head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0  
            latitude  housing_median_age  total_rooms  total_bedrooms  \
longitude                                                               
-124.18    40.790000     